### ISSUE TITLE
README is out of date

### ISSUE THREAD

**Issue by freeekanayaka** [juju/loggo#22]
It mentions:

writer, _, err := loggo.RemoveWriter("default")
// err is non-nil if and only if the name isn't found.
loggo.RegisterWriter("default", writer, loggo.TRACE)

but these APIs have changed.

It would be good if documentation was tested.

**Comment by alertedsnake** [comment]
Is this an abandoned project?  7 months and no response to this issue makes me look elsewhere for libraries.

**Comment by howbazaar** [comment]
No this isn't an abandoned project, however we did miss the original issue.
