### ISSUE TITLE
Multiline Support

### ISSUE THREAD

**Issue by majimboo** [juju/loggo#23]
I noticed that if you did something like `hex.Dump(buffer)` which will be printed in multiple lines only the first line gets prefixed with the information which makes the output ugly. Any idea for a fix?

**Comment by howbazaar** [comment]
This is by design. What I tend to do is output with a new line at the start... or something like this:

```go
// Check first so you don't do extra work
if logger.IsDebugEnabled() {
  lines := strings.Split(hex.Dump, "\n")
  logger.Debugf("Blah blah:\n  %s", strings.Join(lines, "\n  "))
}
```
