### ISSUE TITLE
Time format.

### ISSUE THREAD

**Issue by cydside** [juju/loggo#29]
Hi,
I wonder if you can add a function to set the time format without involve the system environment.
Thanks in advance,

Danilo

**Comment by howbazaar** [comment]
The default output is defined in `formatter.go` and it is pretty simple to replace.

```go
loggo.ReplaceDefaultWriter(
    loggo.NewSimpleWriter(os.Stderr, 
        func(entry loggo.Entry) string {
            ts := entry.Timestamp.In(time.UTC).Format(SOME_FORMAT_STRING)
            // Just get the basename from the filename
            filename := filepath.Base(entry.Filename)
            return fmt.Sprintf("%s %s %s %s:%d %s", ts, entry.Level, entry.Module, filename, entry.Line, entry.Message)
        }))
```

**Comment by cydside** [comment]
Sorry, my fault. I'm talking about the `initTimeFormat()` function, it loads the environment variable LOGGO_TIME_FORMAT(in my opinion it's not the best way in order to get the code portable) or sets "15:04:05". I'd like to have "2006-01-02 15:04:05" and it's simple to do but I'm here to suggest a simple `SetDefaultTimeFormat` function if it's not so much trouble.
Thanks

**Comment by adrianog** [comment]
What's the best / recommended way to format the output to microseconds? ReplaceDefaultWriter golang mechanism, or the LOGGO_TIME_FORMAT environment variable?

**Comment by howbazaar** [comment]
Personally I'd replace the default writer, or propose a SetDefaultTimeFormat function.
