### ISSUE TITLE
Logging to stdout

### ISSUE THREAD

**Issue by DouglasCAdolph** [juju/loggo#33]
Is there a way to configure the logger so that it outputs to **stdout**, rather than **stderr**?

If no, propose to add option to set logging to stdout.

**Comment by howbazaar** [comment]
Sure, just replace the default logger with one confured for stdout.

**Comment by howbazaar** [comment]
Sure...
```go
loggo.ReplaceDefaultWriter(loggo.NewSimpleWriter(os.Stdout, loggo.DefaultFormatter))
```
or for color
```go
loggo.ReplaceDefaultWriter("default", loggocolor.NewWriter(os.Stdout))
```

**Comment by howbazaar** [comment]
Probably not documented in examples, but probably should be. There are the standard godoc, but it probably doesn't help as much if you don't know what you are looking for.
